name: tee-web-prover

on:
    push:
        branches: ["main", "feat/**"]
    pull_request:
        branches: ["main"]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build_and_deploy_tee:
        # Run the job if any of these conditions are true:
        # 1. It's a push to main
        # 2. It's a push to a feature branch
        if: |
            github.event_name == 'push' && github.ref == 'refs/heads/main' ||
            github.event_name == 'push' && startsWith(github.ref, 'refs/heads/feat/')
        uses: ./.github/workflows/build_and_deploy_tee.yaml
        secrets: inherit
